edpm-fee docker images

diff --git a/docker/ubuntu-root/Dockerfile b/docker/ubuntu-root/Dockerfile
--- a/docker/ubuntu-root/Dockerfile
+++ b/docker/ubuntu-root/Dockerfile
@@ -1,18 +1,12 @@
 # Main build command - minimal and self-contained
-  #BUILDX_GIT_LABELS=full docker buildx build \
-  #    --platform linux/amd64,linux/arm64 \
-  #    --tag eicdev/ubuntu-root:latest \
-  #    --push \
-  #    .
-# One line:
-# BUILDX_GIT_LABELS=full docker buildx build --tag eicdev/ubuntu-root:latest --push .
+# docker buildx build --build-arg BUILD_THREADS=24 --tag eicdev/ubuntu-root:latest --push .
 
 FROM ubuntu:24.04
 
 # OCI Image Labels - most automatically populated by buildx via BUILDX_GIT_LABELS
 LABEL org.opencontainers.image.authors="Dmitry Romanov <romanov@jlab.org>" \
-      org.opencontainers.image.url="https://github.com/DarTeots/edpm" \
-      org.opencontainers.image.documentation="https://github.com/DarTeots/edpm/blob/main/README.md" \
+      org.opencontainers.image.url="https://github.com/JeffersonLab/tdis" \
+      org.opencontainers.image.documentation="https://github.com/JeffersonLab/tdis/blob/main/README.md" \
       org.opencontainers.image.vendor="Dmitry Romanov" \
       org.opencontainers.image.licenses="MIT" \
       org.opencontainers.image.title="EIC Ubuntu Development Environment with ROOT" \
@@ -59,72 +53,66 @@ ENV CLICOLOR_FORCE=1      \
     LC_ALL=en_US.UTF-8
 
 # Install EDPM v3 and set the top_dir
-RUN python3 -m pip install --user --upgrade --force-reinstall --break-system-packages ruamel.yaml click appdirs edpm
+RUN python3 -m pip install --user --upgrade --force-reinstall --break-system-packages ruamel.yaml click appdirs
 
 # Set clang as default
 RUN update-alternatives --install /usr/bin/c++ c++ /usr/bin/clang++-18 60
 
-COPY bashrc /root/.bashrc
-RUN dos2unix /root/.bashrc
-
-# RUN yes | unminimize
-
 WORKDIR ${APP_ROOT}
 ENV PATH="$PATH:/root/.local/bin"
 
-# Number of build threads
+
+
+# ---------------------------------------------------------------------------#
+#  Build-time arguments & environment                                        #
+# ---------------------------------------------------------------------------#
 ARG BUILD_THREADS=8
+ARG CXX_STANDARD=20
 
-# Software versions
-ARG VERSION_CERN_ROOT=v6-36-00
+### ---------------------------------------------------------------------- ###
+###          ROOT build (no EDPM)                                          ###
+### ---------------------------------------------------------------------- ###
+ARG CERN_ROOT_VERSION=v6-36-00
+ENV CERN_ROOT_SRC_PATH=${APP_ROOT}/root-src \
+    CERN_ROOT_BLD_PATH=${APP_ROOT}/root-build \
+    CERN_ROOT_INS_PATH=${APP_ROOT}/root
 
-# this is where our edpm plan will be
-ENV EDPM_PLAN_FILE=${APP_ROOT}/plan.edpm.yaml
-ENV EDPM_LOCK_FILE=${APP_ROOT}/plan-lock.edpm.yaml
+RUN set -ex && \
+    # 1. Clone CERN ROOT (shallow, specific tag / branch)
+    git clone --branch ${CERN_ROOT_VERSION} --depth 1 https://github.com/root-project/root.git "${CERN_ROOT_SRC_PATH}" && \
+    \
+    # 2. Configure with CMake in out-of-source build dir
+    mkdir -p "${CERN_ROOT_BLD_PATH}" && cd "${CERN_ROOT_BLD_PATH}" && \
+    cmake \
+      -DCMAKE_INSTALL_PREFIX="${CERN_ROOT_INS_PATH}" \
+      -DCMAKE_BUILD_TYPE=RelWithDebInfo \
+      -DCMAKE_CXX_STANDARD=${CXX_STANDARD} \
+      -Droot7=ON \
+      -Dgdml=ON \
+      -Dxrootd=OFF \
+      -Dmysql=OFF \
+      -Dpythia6=OFF \
+      -Dpythia6_nolink=OFF \
+      -Dpythia8=OFF \
+      -Dhttp=ON \
+      -Wno-dev \
+      "${CERN_ROOT_SRC_PATH}" && \
+    \
+    # 3. Build & install
+    cmake --build . --target install -j"${BUILD_THREADS}" && \
+    \
+    # 4. Clean up build tree to slim the image
+    rm -rf "${CERN_ROOT_BLD_PATH}" "${CERN_ROOT_SRC_PATH}"
 
-# Initialize EDPM and configure global settings
-RUN edpm init &&\
-    edpm --top-dir=${APP_ROOT} &&\
-    edpm config global cxx_standard=20 &&\
-    edpm config global build_threads=${BUILD_THREADS} &&\
-    edpm config global env_bash_out=${APP_ROOT}/env.sh &&\
-    edpm config global env_csh_out="" &&\
-    edpm config global cmake_toolchain_out=${APP_ROOT}/CMakeToolchain.cmake &&\
-    edpm config global cmake_presets_out=${APP_ROOT}/CMakeUserPresets.json &&\
-    edpm env save &&\
-    echo "*** EDPM CONFIGURED ***"
-
-RUN edpm add root@${VERSION_CERN_ROOT} && \
-    edpm config root cmake_custom_flags="-Dcuda=OFF -Dcudnn=OFF -Dtmva-gpu=OFF" && \
-    edpm install root && \
-    edpm clean root
-
-CMD ["bash"]
-
-RUN echo '#!/bin/bash'                                    > /entrypoint.sh &&\
-    echo 'set -e'                                        >> /entrypoint.sh &&\
-    echo ''                                              >> /entrypoint.sh &&\
-    echo '# Source the EDPM environment script (env.sh)' >> /entrypoint.sh &&\
-    echo 'source ${APP_ROOT}/env.sh || true'             >> /entrypoint.sh &&\
-    echo ''                                              >> /entrypoint.sh &&\
-    echo 'exec "$@"'                                     >> /entrypoint.sh
-
-RUN chmod +x /entrypoint.sh
-RUN ls -l /entrypoint.sh  # Verify file exists
-RUN cat /entrypoint.sh    # Verify content
-RUN dos2unix /entrypoint.sh
-ENTRYPOINT ["/entrypoint.sh"]
-
-
-ENV ROOTSYS=${APP_ROOT}/root
-
-ENV PATH="$ROOTSYS/bin:$PATH" \
-    LD_LIBRARY_PATH="$ROOTSYS/lib:${LD_LIBRARY_PATH}" \
-    DYLD_LIBRARY_PATH="$ROOTSYS/lib:${DYLD_LIBRARY_PATH}" \
-    SHLIB_PATH="$ROOTSYS/lib:${SHLIB_PATH}" \
-    LIBPATH="$ROOTSYS/lib:${LIBPATH}" \
-    PYTHONPATH="$ROOTSYS/lib:${PYTHONPATH}" \
-    CMAKE_PREFIX_PATH="$ROOTSYS:${CMAKE_PREFIX_PATH}" \
-    JUPYTER_PATH="$ROOTSYS/etc/notebook:${JUPYTER_PATH}" \
-    JUPYTER_CONFIG_DIR="$ROOTSYS/etc/notebook:${JUPYTER_CONFIG_DIR}" \
+# Export classic ROOT vars. Why like this? This is the most stable way to make environment variables work in any case
+ENV ROOTSYS=${CERN_ROOT_INS_PATH} \
+    PATH="${CERN_ROOT_INS_PATH}/bin:${PATH}" \
+    LD_LIBRARY_PATH="${CERN_ROOT_INS_PATH}/lib" \
+    DYLD_LIBRARY_PATH="${CERN_ROOT_INS_PATH}/lib" \
+    SHLIB_PATH="${CERN_ROOT_INS_PATH}/lib" \
+    LIBPATH="${CERN_ROOT_INS_PATH}/lib" \
+    PYTHONPATH="${CERN_ROOT_INS_PATH}/lib" \
+    CMAKE_PREFIX_PATH="${CERN_ROOT_INS_PATH}" \
+    JUPYTER_PATH="${CERN_ROOT_INS_PATH}/etc/notebook" \
+    JUPYTER_CONFIG_DIR="${CERN_ROOT_INS_PATH}/etc/notebook" \
     CLING_STANDARD_PCH=none
